/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.digestivequestgame.view;

import javax.swing.JFrame;

/**
 *
 * @author AMD
 */
public class TelaMenuProf extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuProf
     */
    public TelaMenuProf() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TelaProfIniciar = new javax.swing.JToggleButton();
        TelaProfJogadores = new javax.swing.JToggleButton();
        TelaProfSair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel1.setText("DigestiveQuest");

        TelaProfIniciar.setBackground(new java.awt.Color(255, 153, 0));
        TelaProfIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TelaProfIniciar.setForeground(new java.awt.Color(255, 255, 255));
        TelaProfIniciar.setText("INICIAR");
        TelaProfIniciar.setBorder(null);
        TelaProfIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaProfIniciarActionPerformed(evt);
            }
        });

        TelaProfJogadores.setBackground(new java.awt.Color(255, 153, 0));
        TelaProfJogadores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TelaProfJogadores.setForeground(new java.awt.Color(255, 255, 255));
        TelaProfJogadores.setText("VER JOGADORES");
        TelaProfJogadores.setBorder(null);
        TelaProfJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaProfJogadoresActionPerformed(evt);
            }
        });

        TelaProfSair.setBackground(new java.awt.Color(255, 153, 0));
        TelaProfSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TelaProfSair.setForeground(new java.awt.Color(255, 255, 255));
        TelaProfSair.setText("SAIR");
        TelaProfSair.setBorder(null);
        TelaProfSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaProfSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TelaProfSair, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TelaProfJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(TelaProfIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(TelaProfIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TelaProfJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TelaProfSair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelaProfJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaProfJogadoresActionPerformed
        TelaJogadores jogadores = new TelaJogadores();
        jogadores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TelaProfJogadoresActionPerformed

    private void TelaProfIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaProfIniciarActionPerformed
        SnakeGame jogo = new SnakeGame();

    // Cria um novo JFrame para exibir o jogo
        JFrame frameJogo = new JFrame("Snake Game");
        frameJogo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fecha apenas o jogo quando fechado
        frameJogo.setResizable(false);
        frameJogo.add(jogo); // Adiciona o jogo ao JFrame
        frameJogo.pack();
        frameJogo.setLocationRelativeTo(null);
        frameJogo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TelaProfIniciarActionPerformed

    private void TelaProfSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaProfSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_TelaProfSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuProf().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TelaProfIniciar;
    private javax.swing.JToggleButton TelaProfJogadores;
    private javax.swing.JToggleButton TelaProfSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
